# Content
core_pages_list:       
  "Home": '/'
  "Semantic Specification": '/spec'
  "Contributors": '/contributors'

user_pages_list:       
  "Per-Platform APIs": '/apis'
  "Instrumentation Use Cases": '/use-cases'

implementor_pages_list:       
  "Implementing OpenTracing": '/implementors'

# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  hard_wrap: false

gems: 
  - jekyll-paginate
  - jekyll-gist
  - jekyll-mentions
  - jekyll-coffeescript

# Permalinks
permalink:        pretty

# Setup
title:            The OpenTracing Project
tagline:          'Consistent, expressive, vendor-neutral APIs for distributed tracing and context propagation'
description:      'Consistent, expressive, vendor-neutral APIs for distributed tracing and context propagation'
url:              http://opentracing.io
baseurl:          /

author:
  name:           'The OpenTracing Authors'
  url:            http://opentracing.io

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/opentracing
